name: A workflow of my Hello World file
on: push

jobs:
  build:
    name: Hello World action
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "HUAN"
      - shell: bash
        run: |
          pwd 
          ls -al
          ping -c 5 192.168.10.29 2>&1 > 10.29.txt
        
